.PHONY: all
all: 3XA3_DevelopmentPlan_Group2L03.pdf

3XA3_DevelopmentPlan_Group2L03.pdf: main.tex
		cp main.tex 3XA3_DevelopmentPlan_Group2L03.tex
	    pdflatex 3XA3_DevelopmentPlan_Group2L03.tex

.PHONY: clean
clean:
	rm 3XA3_DevelopmentPlan_Group2L03*
